version: "3"

services:
  djkhaledv2.0:
    build: .
    image: musicbot
    container_name: djkhaledv2.0
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    environment:
      # - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=youshallnotpass # set password for lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    ports:
      - 2333:2333
    expose:
      - 2333 
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net:
